version: "3.1"

secrets:
  aws_access_key:
    external: true
  aws_secret_access_key:
    external: true

  web:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  datemo:
    image: ezmiller/datemo:0.1.2
    ports:
      - "8080:8080"
    environment:
      - DATEMO_DB_URI="datomic:ddb://datemo/datemo"
      - VIRTUAL_HOST=138.197.7.39
    secrets:
      - aws_access_key
      - aws_secret_access_key

