version: "3.1"

services:
  web:
    image: ezmiller/datemo-nginx-proxy:latest
    ports:
      - "80:80"

  datemo:
    image: ezmiller/datemo:latest
    depends_on:
      - web
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=104.131.119.148

