version: "3.1"

secrets:
  aws_access_key:
    external: true
  aws_secret_access_key:
    external: true

services:
  web:
    image: ezmiller/datemo-nginx-proxy:latest
    ports:
      - "80:80"

  datemo:
    image: ezmiller/datemo:latest
    environment:
      - DATOMIC_CLOUD_STACK_NAME=datemo
    depends_on:
      - web
      - datomic-socks-proxy
    ports:
      - "8080:8080"
    secrets:
      - aws_access_key
      - aws_secret_access_key

