version: "3.1"

secrets:
  aws_access_key:
    external: true
  aws_secret_access_key:
    external: true

services:
  # web:
  #   image: nginx
  #   volumes:
  #    - ./server.template:/etc/nginx/conf.d/server.template
  #   ports:
  #    - "80:80"
  #   environment:
  #    - NGINX_PORT=80
  #    - BACKEND_PORT=8080
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/server.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  #
  datemo:
    image: ezmiller/datemo:0.1.2
    ports:
      - "80:80"
    secrets:
      - aws_access_key
      - aws_secret_access_key

