version: "3.1"

secrets:
  aws_access_key:
    external: true
  aws_secret_access_key:
    external: true

services:
  web:
    image: ezmiller/datemo-nginx-proxy:latest
    ports:
      - "80:80"

  datomic-socks-proxy:
    image: ezmiller/datomic-socks-proxy:latest
    ports:
      - "8182:8182"
    environment:
      - PORT=8182
    secrets:
      - aws_access_key
      - aws_secret_access_key

  datemo:
    image: ezmiller/datemo:latest
    depends_on:
      - web
      - datomic-socks-proxy
    ports:
      - "8080:8080"

